#include <ctype.h>
#include <dirent.h>
#include <getopt.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    if (!line || !syscall_name || !time)
        return -1;

    char *s = line;
    while (*s && isspace((unsigned char)*s))
        s++;

    char *lp = strchr(s, '(');
    char *rp = strrchr(s, ')');
    if (!lp || !rp || lp >= rp)
        return -1;

    char *name_end = lp;
    while (name_end > s && isspace((unsigned char)name_end[-1]))
        name_end--;

    size_t name_len = (size_t)(name_end - s);
    if (name_len == 0)
        return -1;

    memcpy(syscall_name, s, name_len);
    syscall_name[name_len] = '\0';

    char *lt = strchr(rp, '<');
    char *gt = lt ? strchr(lt, '>') : NULL;
    if (!lt || !gt || lt >= gt)
        return -1;

    char tmp[64];
    size_t dur_len = (size_t)(gt - lt - 1);
    if (dur_len == 0 || dur_len >= sizeof(tmp))
        return -1;

    memcpy(tmp, lt + 1, dur_len);
    tmp[dur_len] = '\0';

    char *end = NULL;
    *time = strtod(tmp, &end);
    if (end == tmp)
        return -1;

    return 0;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {

    if (argc < 2) {
        fprintf(stderr, "usage: %s command [args...]\n", argv[0]);
        return EXIT_FAILURE;
    }

    char **exec_argv = calloc(argc + 2, sizeof(char *));
    if (exec_argv == NULL) {
        perror("calloc");
        return EXIT_FAILURE;
    }
    exec_argv[0] = "strace";
    exec_argv[1] = "-T";

    char *exec_envp[] = {
        "PATH=/usr/local/bin:/usr/bin:/bin",
        NULL,
    };

    for (int i = 1; i < argc; i++) {
        exec_argv[i + 1] = argv[i];
    }
    exec_argv[argc + 1] = NULL;

    for (int i = 0; i < argc + 2; i++) {
        printf("exec_argv[%d]: %s\n", i, exec_argv[i]);
    }

    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe");
        exit(EXIT_FAILURE);
    }
    printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
    pid_t pid = fork();
    if (pid == 0) {
        printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
        close(pipefd[0]);
        dup2(pipefd[1], STDERR_FILENO);
        close(pipefd[1]);

        execve("/usr/bin/strace", exec_argv, exec_envp);
        perror(argv[0]);
        exit(EXIT_FAILURE);

    } else if (pid < 0) {
        perror("fork");
        exit(EXIT_FAILURE);
    }

    printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
    close(pipefd[1]);
    dup2(pipefd[0], STDIN_FILENO);

    FILE *in = fdopen(pipefd[0], "r");
    char line[4096];

    while (fgets(line, sizeof(line), in) != NULL) {
        printf("child received: %s", line);
        char syscall_name[64];
        double time;
        if (parse_strace_line(line, syscall_name, &time) == 0) {
            printf("syscall: %s, time: %f\n", syscall_name, time);
        }
    }

    close(pipefd[0]);

    return 0;
}
