#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {
    char *exec_argv[] = {
        "strace",
        "ls",
        NULL,
    };
    char *exec_envp[] = {
        "PATH=/usr/local/bin:/usr/bin:/bin",
        "HOME=/home/feng",

        NULL,
    };

    for (int i = 0; i < argc; i++) {
        printf("argv[%d]: %s\n", i, argv[i]);
    }
    for (int i = 1; i < argc; i++) {
        exec_argv[i] = argv[i];
    }
    for (int i = 0; i < argc; i++) {
        printf("exec_argv[%d]: %s\n", i, exec_argv[i]);
    }
    execve("strace", exec_argv, exec_envp);
    perror(argv[0]);
    exit(EXIT_FAILURE);
}
