#include <ctype.h>
#include <dirent.h>
#include <getopt.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <unistd.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
}

void print_top_syscalls(syscall_stats *stats, int n) {
}

int main(int argc, char *argv[]) {

    if (argc < 2) {
        fprintf(stderr, "usage: %s command [args...]\n", argv[0]);
        return EXIT_FAILURE;
    }

    char **exec_argv = calloc(argc + 2, sizeof(char *));
    if (exec_argv == NULL) {
        perror("calloc");
        return EXIT_FAILURE;
    }
    exec_argv[0] = "strace";
    exec_argv[1] = "-T";

    char *exec_envp[] = {
        "PATH=/usr/local/bin:/usr/bin:/bin",
        NULL,
    };

    for (int i = 1; i < argc; i++) {
        exec_argv[i + 1] = argv[i];
    }
    exec_argv[argc + 1] = NULL;

    for (int i = 0; i < argc + 2; i++) {
        printf("exec_argv[%d]: %s\n", i, exec_argv[i]);
    }

    int pipefd[2];
    if (pipe(pipefd) == -1) {
        perror("pipe");
        exit(EXIT_FAILURE);
    }
    printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
    pid_t pid = fork();
    if (pid == 0) {
        printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
        close(pipefd[0]);
        dup2(pipefd[1], STDERR_FILENO);
        close(pipefd[1]);

        execve("/usr/bin/strace", exec_argv, exec_envp);
        perror(argv[0]);
        exit(EXIT_FAILURE);

    } else if (pid < 0) {
        perror("fork");
        exit(EXIT_FAILURE);
    }

    printf("read end = %d, write end = %d\n", pipefd[0], pipefd[1]);
    close(pipefd[1]);
    dup2(pipefd[0], STDIN_FILENO);

    char buf[4096];
    int n;
    while (n > 0) {
        n = read(pipefd[0], buf, sizeof(buf) - 1);
        if (n > 0) {
            buf[n] = '\0';
            printf("child received: %s\n", buf);
        }
    }

    close(pipefd[0]);

    return 0;
}
